name: MacOS
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  build-64-release:
    runs-on: "macos-latest"
    name: Build 64-Bit Release

    steps:
      - uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule update --init --remote --recursive

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Setup Discord SDK
        run: sh ./setup.sh

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        run: |
          scons platform=osx target=release bits=64

      - name: Remove SDK DyLib
        run: rm demo/bin/osx-64/libdiscord_game_sdk.dylib

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_64_release
          path: demo/bin/osx-64/*

  build-64-debug:
    runs-on: "macos-latest"
    name: Build 64-Bit Debug

    steps:
      - uses: actions/checkout@v2

      - name: Update Submodules
        run: |
          git submodule update --init --remote --recursive

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Setup Discord SDK
        run: sh ./setup.sh

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        run: |
          scons platform=osx target=debug bits=64

      - name: Remove SDK DyLib
        run: rm demo/bin/osx-64/libdiscord_game_sdk.dylib

      - uses: actions/upload-artifact@v2
        with:
          name: gdsdk_64_debug
          path: demo/bin/osx-64/*
